# Generated by Django 3.2.8 on 2021-10-24 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20211024_1856'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='FileModel',
        ),
    ]
